import { GET_ATTESTATIONS_FOR_RECIPIENT } from "./GET_ATTESTATIONS_FOR_RECIPIENT";
import { GET_ATTESTATION_BY_UID } from "./GET_ATTESTATION_BY_UID";

export { GET_ATTESTATIONS_FOR_RECIPIENT, GET_ATTESTATION_BY_UID };
